### ISSUE TITLE
plinkSTR issue: tool not working 

### ISSUE THREAD

**Issue by vishalrossi** [gymreklab/TRTools#103]
Hi,

I am trying to run plinkSTR for association analysis using the docker pull request (docker pull gymreklab/str-toolkit:latest).

Tools like dumpSTR, postmaSTR, mergeSTR work through the docker image, except plinkSTR (screenshots attached).

Can you please guide on how to make plinkSTR work.
<img width="824" alt="Screen Shot 2020-07-08 at 15 04 34" src="https://user-images.githubusercontent.com/25217454/87033206-78b92c00-c1ee-11ea-9f7f-f1808cdb3cf8.png">
<img width="725" alt="Screen Shot 2020-07-08 at 15 04 57" src="https://user-images.githubusercontent.com/25217454/87033210-7bb41c80-c1ee-11ea-895a-b873725e5a64.png">
<img width="524" alt="Screen Shot 2020-07-08 at 15 05 33" src="https://user-images.githubusercontent.com/25217454/87033213-7c4cb300-c1ee-11ea-9fce-1bd2e4fa2794.png">
<img width="586" alt="Screen Shot 2020-07-08 at 15 05 50" src="https://user-images.githubusercontent.com/25217454/87033214-7ce54980-c1ee-11ea-96ce-0656fcce14a1.png">

**Comment by shubhamsaini** [comment]
plinkSTR has its own repository now. Please check https://github.com/gymreklab/plinkSTR
