### ISSUE TITLE
Adding BCFtools to docker file

### ISSUE THREAD

**Issue by ambenj** [gymreklab/TRTools#124]
Hello! I'm currently using the docker file to run gangSTR and then mergeSTR which requires sorted, zipped, and indexed VCFs. From what I can tell, the docker image doesn't include bcftools, which is needed for sorting the VCF output from gangSTR. Can bcftools be added to the docker file? Or if there is a way to sort VCF files with the current build can you let me know how to do it? Thank you!

**Comment by nmmsv** [comment]
Hi Alyssa, 
Sorry for my delayed response. We have only included the packages that were required for running TRTools. However, we can also add bcftools to the docker file as it's a useful utility. Would you be able to make the change and submit a PR? I'll be happy to help and review.
Thanks.
