### ISSUE TITLE
Conflicting refs found at ****

### ISSUE THREAD

**Issue by AhmedArslan** [gymreklab/TRTools#125]
Can you please explain why I am getting this warning message, if its a big problem, then how can I eliminate it?

**Comment by gymreklab** [comment]
Do you have any more info about the command you are running? This message can happen when trying to run mergeSTR if it encounters two VCFs with the same chrom/pos but different reference alleles. This case is currently not handled and a tool to handle those types of more complex merges is in progress.

**Comment by AhmedArslan** [comment]
Hi any progress to handle this warning?
