### ISSUE TITLE
qcSTR TypeError when analyzing multiple samples

### ISSUE THREAD

**Issue by MKBakker** [gymreklab/TRTools#142]
**The issue**
When I use qcSTR with multiple samples I run into an error I'm unable to solve. 
I reproduced the error using the example vcf files trio_chr21_gangstr.sorted.vcf.gz and trio_chr21_gangstr.sorted.vcf.gz.tbi in the GitHub repository.

This error only occurs when running qcSTR on multiple samples. When selecting a single sample using --samples, or loading a single-sample vcf file the function "OutputSampleCallrate" is skipped and the rest of the qcSTR script runs without error.

**My command**
```
qcSTR \
--vcf trio_chr21_gangstr.sorted.vcf.gz \
--out qcSTR.output
```

**The output I get**
Producing qcSTR.output-diffref-bias.pdf ... Done.
Producing qcSTR.output-sample-callnum.pdf ... Traceback (most recent call last):
  File "/hpc/hers_en/jvanvugt/Software/miniconda3/envs/TRTools/bin/qcSTR", line 10, in <module>
    sys.exit(run())
  File "/hpc/hers_en/jvanvugt/Software/miniconda3/envs/TRTools/lib/python3.6/site-packages/trtools/qcSTR/qcSTR.py", line 642, in run
    retcode = main(args)
  File "/hpc/hers_en/jvanvugt/Software/miniconda3/envs/TRTools/lib/python3.6/site-packages/trtools/qcSTR/qcSTR.py", line 555, in main
    OutputSampleCallrate(sample_calls, args.out+"-sample-callnum.pdf")
  File "/hpc/hers_en/jvanvugt/Software/miniconda3/envs/TRTools/lib/python3.6/site-packages/trtools/qcSTR/qcSTR.py", line 140, in OutputSampleCallrate
    data = pd.DataFrame({"sample": samples, "numcalls": [sample_calls[key] for key in samples]})
  File "/hpc/hers_en/jvanvugt/Software/miniconda3/envs/TRTools/lib/python3.6/site-packages/pandas/core/frame.py", line 468, in __init__
    mgr = init_dict(data, index, columns, dtype=dtype)
  File "/hpc/hers_en/jvanvugt/Software/miniconda3/envs/TRTools/lib/python3.6/site-packages/pandas/core/internals/construction.py", line 283, in init_dict
    return arrays_to_mgr(arrays, data_names, index, columns, dtype=dtype)
  File "/hpc/hers_en/jvanvugt/Software/miniconda3/envs/TRTools/lib/python3.6/site-packages/pandas/core/internals/construction.py", line 83, in arrays_to_mgr
    arrays = _homogenize(arrays, index, dtype)
  File "/hpc/hers_en/jvanvugt/Software/miniconda3/envs/TRTools/lib/python3.6/site-packages/pandas/core/internals/construction.py", line 352, in _homogenize
    val, index, dtype=dtype, copy=False, raise_cast_failure=False
  File "/hpc/hers_en/jvanvugt/Software/miniconda3/envs/TRTools/lib/python3.6/site-packages/pandas/core/construction.py", line 452, in sanitize_array
    raise TypeError("Set type is unordered")
TypeError: Set type is unordered

**What else I tried**
I tried using --vcftype gangstr
And tried using --use-length (because of the length type warning), but this option is not supported by qcSTR
Running qcSTR on a vcf file with a single sample, or selection a single sample using --samples will skip the error-causing part. But this obviously means the multiple-sample options cannot be used.

**Environment**
The conda environment I use:
Name	Version	Build	Channel
_libgcc_mutex	0.1	main	
bedtools	2.29.2	hc088bd4_0	bioconda
blas	1.0	mkl	
bzip2	1.0.8	h7b6447c_0	
ca-certificates	2020.7.22	0	
certifi	2020.6.20	py36_0	
curl	7.71.1	hbc83047_1	
cycler	0.10.0	py36_0	
freetype	2.10.2	h5ab3b9f_0	
intel-openmp	2020.2	254	
joblib	0.16.0	py_0	
jpeg	9b	h024ee3a_2	
kiwisolver	1.2.0	py36hfd86e86_0	
krb5	1.18.2	h173b8e3_0	
lcms2	2.11	h396b838_0	
ld_impl_linux-64	2.33.1	h53a641e_7	
libcurl	7.71.1	h20c2e04_1	
libdeflate	1.0	h14c3975_1	bioconda
libedit	3.1.20191231	h14c3975_1	
libffi	3.3	he6710b0_2	
libgcc-ng	9.1.0	hdf63c60_0	
libgfortran-ng	7.3.0	hdf63c60_0	
libpng	1.6.37	hbc83047_0	
libssh2	1.9.0	h1ba5d50_1	
libstdcxx-ng	9.1.0	hdf63c60_0	
libtiff	4.1.0	h2733197_1	
lz4-c	1.9.2	he6710b0_1	
matplotlib-base	3.3.1	py36h817c723_0	
mkl	2020.2	256	
mkl-service	2.3.0	py36he904b0f_0	
mkl_fft	1.2.0	py36h23d657b_0	
mkl_random	1.1.1	py36h0573a6f_0	
ncurses	6.2	he6710b0_1	
numpy	1.19.1	py36hbc911f0_0	
numpy-base	1.19.1	py36hfa32c7d_0	
olefile	0.46	py36_0	
openssl	1.1.1g	h7b6447c_0	
pandas	1.1.1	py36he6710b0_0	
pillow	7.2.0	py36hb39fc2d_0	
pip	20.2.2	py36_0	
pybedtools	0.8.1	py36he513fc3_0	bioconda
pyparsing	2.4.7	py_0	
pysam	0.15.3	py36hda2845c_1	bioconda
python	3.6.12	hcff3b4d_2	
python-dateutil	2.8.1	py_0	
pytz	2020.1	py_0	
pyvcf	0.6.8	py36_0	bioconda
readline	8.0	h7b6447c_0	
scikit-learn	0.23.2	py36h0573a6f_0	
scipy	1.5.2	py36h0b6359f_0	
setuptools	49.6.0	py36_0	
six	1.15.0	py_0	
sqlite	3.33.0	h62c20be_0	
threadpoolctl	2.1.0	pyh5ca1d4c_0	
tk	8.6.10	hbc83047_0	
tornado	6.0.4	py36h7b6447c_1	
trtools	3.0.2	py_0	bioconda
wheel	0.35.1	py_0	
xz	5.2.5	h7b6447c_0	
zlib	1.2.11	h7b6447c_3	
zstd	1.4.5	h9ceee32_0	

I hope you can help me out! Thanks,
Mark

**Comment by reveloff-ucsd** [comment]
As of today, using Python 3.9.13, I was unable to reproduce this error. Please let me know if you're still getting this error and how you produced it. From what I can gather, "set type unordered" is an error used predominantly by Pandas when creating dataframes from lists, so I suspect this is a version incompatibility error that has since been resolved.

**Comment by MKBakker** [comment]
@reveloff-ucsd I think that is exactly what happened. In the meantime I was able to run qcSTR without error with python=3.7.13 and pandas=1.2.4

created using conda:
conda create --name TRTools
source activate TRTools
conda install -c bioconda trtools
