### ISSUE TITLE
compareSTR compatibility with STR imputation results

### ISSUE THREAD

**Issue by bibb** [gymreklab/TRTools#145]
Hello,

I've been trying to use compareSTR to compare STR genotypes from a GWAS dataset imputed with the STR reference panel (1000G) against the same samples, but sequenced (whole-genome) and called with gangSTR. CompareSTR says it allows calls from hipSTR which is the base of the STR imputation, but the software doesn't recognize the vcftype. Is is possible to make compareSTR suitable to read imputed VCFs files? the imputation of STRs was done with Beagle as recommended.
Thanks!
~B

**Comment by LiterallyUniqueLogin** [comment]
Hi B,

Sorry for the slow response. TRtools currently doesn't support Beagle, but it's a relative quick change to fix that. What's your use case (which tools are you intending to use)?

There's a catch. Beagle emits two types of output: hardcalls (i.e. this sample has genotype allele-1/allele-2) and probabilities (AP or GP format fields, which give a percent chance to each sample for each possible genotype). So far the tools have only been designed to work with hardcalls and not probabilities - adding the ability to read Beagle hardcall input won't change that. But for imputed callsets, probabilities are potentially more suited to downstream analyses like association testing.

If you desire to use the probabilities, then TRTools isn't the right tool for that at the moment (unless you want to contribute to making it so). If you plan on using the hardcalls, then we can make that work.

**Comment by bibb** [comment]
Hello,
Thank you for your answer. It's fine to use Beagle hardcalls for the task I have to do. I have to calculate the concordance between the imputed genotypes and the gangSTR called genotypes for the same samples. It's like comparing HipSTR vs gangSTR but this will be imputed hardcalls vs gangSTR. I'll appreciate your help.

~B

**Comment by LiterallyUniqueLogin** [comment]
Well, it took much longer than desired, but TRTools now supports VCFs imputed by Beagle.

If you're still interested in that, read the short section of the docs [here](https://trtools.readthedocs.io/en/latest/CALLERS.html#beagle) for a description of the script that you need to run on the Beagle VCF prior to using it with TRTools. Once that script is run, using Beagle with TRTools should be pretty seamless. Let us know if you have any issues, questions, or documentation suggestions!
