### ISSUE TITLE
[CompareSTR] Typo in condition and redundant condition

### ISSUE THREAD

**Issue by Kulivox** [gymreklab/TRTools#146]
The condition on line 821 in this snippet contains a typo, variable 'is_min' should not be enclosed in brackets because it creates a nested list. 'all()' built in function evaluates to True on nested non empty lists, therefore, this condition will always evaluate to True. The second, nested condition on line 822 hides this bug, and is unnecessary, because contents of variable 'is_min' are based on information about positions and chrom. ids of the two records that are being compared. 
https://github.com/gymreklab/TRTools/blob/eac7523a5eef740fe4eaa7aa9b51b3480eb59a60/trtools/compareSTR/compareSTR.py#L812-L831

Checks on previous lines ensure that is_min is always list of two bools.

Fix: 
```py
    while not done:
        if any([item is None for item in current_records]): break
        if args.numrecords is not None and num_records >= args.numrecords: break
        if args.verbose: mergeutils.DebugPrintRecordLocations(current_records, is_min)
        if mergeutils.CheckMin(is_min): return 1
        if all(is_min):
            UpdateComparisonResults(trh.HarmonizeRecord(vcftype1, current_records[0]), \
                                    trh.HarmonizeRecord(vcftype2, current_records[1]), \
                                    sample_idxs,
                                    args.ignore_phasing, args.period,
                                    format_fields, format_bins,
                                    args.stratify_file,
                                    overall_results, locus_results,
                                    sample_results, bubble_results)
```
This change doesn't break current tests

**Comment by LiterallyUniqueLogin** [comment]
Done!
