### ISSUE TITLE
ValueError: Unexpected error. Stuck in infinite loop and exiting.

### ISSUE THREAD

**Issue by jayala** [gymreklab/TRTools#160]
Hello, I tried to merge two VCFs (attaching the files) from HipSTR. They both were processed with the same parameters and same BED in HipSTR.

Files used:
[HGDP00001.vcf.gz](https://github.com/gymreklab/TRTools/files/9021159/HGDP00001.vcf.gz)
[HGDP00005.vcf.gz](https://github.com/gymreklab/TRTools/files/9021161/HGDP00005.vcf.gz)

And it is returning the following error:

```
mergeSTR --verbose --vcfs HGDP00001.vcf.gz,HGDP00005.vcf.gz --out merge --vcftype hipstr 
chr1:230769615:True	chr1:230769615:True
chr10:129294244:True	chr10:129294244:True
chr11:2171088:True	chr11:2171088:True
chr12:5983969:True	chr12:5983969:True
chr12:12297020:True	chr12:12297020:True
chr13:82148025:True	chr13:82148025:True
chr15:96831014:True	chr15:96831014:True
chr16:86352702:True	chr16:86352702:True
chr18:63281667:True	chr18:63281667:True
chr19:29926235:True	chr19:29926235:True
chr2:1489653:True	chr2:1489653:True
chr2:68011947:True	chr2:68011947:True
chr2:218014859:True	chr2:218014859:True
chr21:43636210:True	chr21:43636210:True
chr22:37140287:False	chr3:45540739:False
Traceback (most recent call last):
  File "/home/jesus/Proyectos/STR-HGDP-MERGE929/env/bin/mergeSTR", line 8, in <module>
    sys.exit(run())
  File "/home/jesus/Proyectos/STR-HGDP-MERGE929/env/lib/python3.10/site-packages/trtools/mergeSTR/mergeSTR.py", line 644, in run
    retcode = main(args)
  File "/home/jesus/Proyectos/STR-HGDP-MERGE929/env/lib/python3.10/site-packages/trtools/mergeSTR/mergeSTR.py", line 634, in main
    if mergeutils.CheckMin(increment): return 1
  File "/home/jesus/Proyectos/STR-HGDP-MERGE929/env/lib/python3.10/site-packages/trtools/utils/mergeutils.py", line 347, in CheckMin
    raise ValueError("Unexpected error. Stuck in infinite loop and exiting.")
ValueError: Unexpected error. Stuck in infinite loop and exiting.
``` 
Is there something I'm doing wrong here?
Thanks in advance.

**Comment by yli091230** [comment]
Hi Jayla,

Thanks for pointing this out. I found this error is due to a bug in the mergeUtility tools. I have fixed the bug and tested. I have submitted a pull request to integrate the fix into develop branch, here is the link for the pull request https://github.com/gymreklab/TRTools/pull/159. Once the pull request be merged, you can get the update code from the develop branch. Let me know if there is any another question.

**Comment by jayala** [comment]
Awesome, I'll try it out! Thanks!
