### ISSUE TITLE
Multiple pairwise comparisons

### ISSUE THREAD

**Issue by b2jia** [gymreklab/TRTools#76]
We have generated multiple VCFs from several different samples using GangSTR, but would like to compare across all possible pairs. We see that TRTools has ```compareSTR``` which allows comparison of two callsets, is there functionality to allow comparisons for more than two?

Thank you!

**Comment by nmmsv** [comment]
Hi @b2jia 
compareSTR does not have that option yet. I don't think we plan to implement such functionality into the method, but I believe you can perform this task by using a wrapper script and having an instance of compareSTR for each comparison.
Hope this helps.
Best,
Nima
